### ISSUE TITLE
Wireless Crfating terminal

### ISSUE THREAD

**Issue by Michi2670** [FTBTeam/FTB-Presents-Direwolf20-1.12#98] opened 2019-02-07 15:21 UTC
I have crafted the wireless crafting terminal from the wireless crafting terminal 2 mod and id doesn´t work.
I can only put a half stack out when i use Right click, i cant put out one item or a complete stack, and i also cant put items in, also not with the magnet upgrade.
The normal AE2 wireless terminal works perfectly.
I´m playing on a Server but thats not the Problem in singleplayer is also doesn´t work.
I m playinng the Version 2.4.0

**Comment by Retovath** [comment] 2019-02-11 21:55
The issue is that ae2 rv6 requires wireless crafting terminal version 3.10.80 or later.
https://github.com/scalda/Foolcraft_3/issues/306

**Comment by SnowShock35** [comment] 2019-03-17 11:19
This has been fixed in the new version of the pack and will be released in a day or so.

Thanks for your issue submission and patience.

**Closed as completed** 2019-03-19 11:58 UTC
Labels: Priority: Medium :warning:, Category: Mods :memo:, State: Fixed :heavy_check_mark:, Cause: Mod :page_facing_up:
