### ISSUE TITLE
MeeCreeps' Creep Cube Duplicates (x2) Thermal Expansion

### ISSUE THREAD

**Issue by TwoPointInfinity** [FTBTeam/FTB-Presents-Direwolf20-1.12#47] opened 2018-08-12 00:07 UTC
* **Modpack Version**: FTB Direwolf20 modpack version 2.2.0 release (8/11/18) & 2.1.0

* **Issue**: When used to flatten an area any MeeCreep will drop 2 of the broken block/machine from thermal expansion. When done on a strongbox full of items all items will be duplicated inside the strongbox (no matter what items they are inside or what mod they're from), as will all other inventories from Thermal Expansion including fluid tanks. I saw one user duplicate enchanted (with Holding) resonant fluid tanks of gelid cryotheum.

* **Repeatable?**: Yes. 

* **Mod/s Affected**: Thermal Expansion **AS FAR AS I KNOW**. I have not personally tested this on other mods. But I suggest someone place down one machine from every mod and break it with meecreeps.

* **Known Fix**: Pester Direwolf to fix the MeeCreeps we love using his mod but meecreeps are disabled on our server until they're fixed or otherwise permanently removed.

**Comment by SnowShock35** [comment] 2018-09-07 10:04
Hello @TwoPointInfinity 

Thank you for your contribution to the FTB Presents Direwolf20 1.12 mod-pack. Your involvement greatly helps to improve the quality of the product and keep it bug-free and more enjoyable for everyone. Without your input, the pack would cease to be as good as it is. 

As it stands right now, I am unable to circumvent this issue in any way. I've spoken with McJty and even he's puzzled as to why this is happening. 

I will update this issue when either of the following happens:

1. The mod causing the issue is fixed.
2. McJty adds a blacklist of blocks that MeeCreeps can break to circumvent this issue.

Many thanks once again for your engagement here on the FTBTeam's GitHub.

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈

**Comment by SnowShock35** [comment] 2019-03-16 17:36
Hi @TwoPointInfinity,

I have confirmed that this issue has been fixed in the upcoming 2.5.0 version of the mod pack. Please stay tuned for a beta release later this week.

Many thanks for your patients.
SnowShock35.

**Closed** 2019-03-19 11:58 UTC
Labels: Category: Mods :memo:, Cause: Cross-mod :twisted_rightwards_arrows:, Priority: High :boom:, State: Fixed in Dev :hammer_and_wrench:
