### ISSUE TITLE
Can't load a game after exiting to main menu without restarting mod pack

### ISSUE THREAD

**Issue by crwoody** [FTBTeam/FTB-Presents-Direwolf20-1.12#32] opened 2018-07-22 21:00 UTC
* **Modpack Version**: 2.1

* **Issue**: After saving and exiting game to main menu can't open any game or start a new one.  When restarting from twitch launcher minecraft loader says a minecraft instance is running.

* **Link to Log or Crash File Paste**:  Game does not crash

* **Is it Repeatable?**: yes

**Comment by Siniq** [comment] 2018-07-22 22:16
This very likely an Immersive Engineering bug, as I had the same problem. See Issue #29.

**Comment by SnowShock35** [comment] 2018-07-23 08:32
Duplicate of #29.

**Closed** 2018-07-23 08:31 UTC
Labels: Bug, Duplicate, Mod Issue
