### ISSUE TITLE
Boots of the traveler duplicating and dank/null/ disappearing. Related events.

### ISSUE THREAD

**Issue by Marvin21st** [FTBTeam/FTB-Presents-Direwolf20-1.12#92] opened 2019-01-06 04:14 UTC
* **Modpack Version**: FTB presents Direwolf20 1.12
* **Issue**: While wearing boots of the traveler when opening /dank/null (yellow) and end up with a duplicate pair of boots and null box disappears. Sometimes comes back (have not worked out how or if this is repeatable) Only happens when wearing boots. Boots can be in inventory with no effect.

* **Link to Log or Crash File Paste**: <none

* **Is it Repeatable?**: yes
* **Mod/s Affected**: Thaumcraft, /dank/null

* **Known Fix**: log out and back in. always fixes. Sometimes it changes back but Im not sure how I did it.

Thanks

**Comment by SnowShock35** [comment] 2019-03-16 22:43
Thank you for reporting this issue. I will report this to the respective author.

**Comment by SnowShock35** [comment] 2019-03-19 14:55
Just a quick update for you: 

It seems this bug isn't the fault of Dank Null or Thaumcraft or both of them but a more complex issue involving several unknown mods or the combination of lots of mods.

**Comment by SnowShock35** [comment] 2019-03-19 14:55
@p455w0rd Any clue as to what might be causing this issue in the latest version of the Direwolf20 mod pack?

**Comment by p455w0rd** [comment] 2019-04-04 08:52
Sorry for only just seeing this. For now use the next-to-latest version..there is a dupe bug, but it's not super common and it's better than having items deleted. I'll be getting the new update (which is a rewrite) in the next few days (hopefully). I am finally at a point that I can make this priority.

**Comment by SnowShock35** [comment] 2019-04-16 09:14
Thanks for letting me know @p455w0rd. I'll sort it once I'm done with uni deadlines in a couple weeks time.

**Comment by p455w0rd** [comment] 2019-04-17 01:38
Yeah..so I ended up ditching that rewrite and starting over again, this time I have brandon3055 helping me, so maybe we can get this squashed once and for all :)

**Comment by SnowShock35** [comment] 2019-05-13 13:33
@p455w0rd Brilliant! Let me know if you have anything to try at some stage or another.

**Comment by 016Nojr** [comment] 2021-04-27 18:43
Seems to be fixed now, I cant reproduce it.

**Closed as completed by 016Nojr** 2021-04-27 18:43 UTC
Labels: Priority: High :boom:, Category: Mods :memo:, State: Fixed :heavy_check_mark:, Cause: Mod :page_facing_up:
