### ISSUE TITLE
Morph crash while changing dimensions 

### ISSUE THREAD

**Issue by gcheezydog** [FTBTeam/FTB-Presents-Direwolf20-1.12#8] opened 2018-07-03 21:34 UTC
* **Modpack Version**: 2.0.0 

* **Issue**:  hard crash when teleporting through mining portal while morphing 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/fe4e3a87 

* **Is it Repeatable?**:  yes 

* **Mod/s Affected**:  Morph-1.12.2-7.1.2 

* **Known Fix**:

**Comment by SnowShock35** [comment] 2018-07-11 18:48
Thanks for the report. I can confirm that the issue is consistent. I've since spoken to the mod author of Morph who has asked me to tell you to avoid morphing in portals until the issue is fixed. It could be sometime before it is fixed due to the author's busy schedule. However, the issue is now known and will be fixed in due course. 

Thanks for helping to better the packs stability. 👍

**Comment by iChun** [comment] 2019-03-02 00:45
Should be addressed in Morph 7.1.3 (when released)

**Comment by SnowShock35** [comment] 2019-03-16 17:20
Hi @gcheezydog,

As of update 2.1.5, this issue will be fixed. 

Thank you for your patients.

**Closed** 2019-03-19 11:58 UTC
Labels: Category: Mods :memo:, Cause: Mod :page_facing_up:, Priority: Low :sunrise_over_mountains:, State: Fixed in Dev :hammer_and_wrench:
